import React, { FC, useState } from 'react';
import { Button, DatePicker, Input, Modal, message } from 'antd';
import { Plus } from 'lucide-react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import todoServices from '../services/service';
import { Dayjs } from 'dayjs';

interface FormState {
  todo: string;
  date: string | null;
}

const AddModal: FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [form, setForm] = useState<FormState>({
    todo: '',
    date: null,
  });
  const queryClient = useQueryClient();

  const { mutate: addTodo, isPending } = useMutation({
    mutationFn: todoServices.addTodo,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['todos'] });
      setIsOpen(false);
      resetForm();
      message.success('Task added successfully!');
    },
    onError: (error) => {
      console.error('Add task failed:', error);
      message.error('Failed to add task');
    },
  });

  const resetForm = () => {
    setForm({ todo: '', date: null });
  };

  const handleDateChange = (date: Dayjs | null) => {
    setForm(prev => ({
      ...prev,
      date: date ? date.format('YYYY-MM-DD') : null,
    }));
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm(prev => ({
      ...prev,
      todo: e.target.value,
    }));
  };

  const handleAdd = () => {
    if (!form.todo || !form.date) {
      message.warning('Please fill in all required fields');
      return;
    }

    addTodo({
      todo_id: '', // This will be generated by the backend
      todo: form.todo,
      date: form.date,
      isCompleted: false,
    });
  };

  return (
    <>
      <Button
        type="primary"
        icon={<Plus size={16} />}
        onClick={() => setIsOpen(true)}
      >
        New Task
      </Button>

      <Modal
        title="New Task"
        open={isOpen}
        onCancel={() => setIsOpen(false)}
        destroyOnClose
        footer={[
          <Button
            key="cancel"
            onClick={() => setIsOpen(false)}
            disabled={isPending}
          >
            Cancel
          </Button>,
          <Button
            key="submit"
            type="primary"
            onClick={handleAdd}
            loading={isPending}
            disabled={!form.todo || !form.date}
          >
            {isPending ? 'Adding...' : 'Add'}
          </Button>,
        ]}
      >
        <div className="space-y-3">
          <div className='space-y-1'>
            <label htmlFor="todo">Task</label>
            <Input
              type="text"
              id="todo"
              placeholder="What you're gonna do?"
              value={form.todo}
              onChange={handleInputChange}
              disabled={isPending}
              required
            />
          </div>
          <div className='space-y-1'>
            <label htmlFor="date">Date</label>
            <DatePicker
              id="date"
              className="w-full"
              onChange={handleDateChange}
              disabled={isPending}
              required
            />
          </div>
        </div>
      </Modal>
    </>
  );
};

export default AddModal;